import { useState } from "react";
import { FileText, Download, Loader2, Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useOnboarding } from "@/context/OnboardingContext";
import { callAI } from "@/lib/ai";

interface AppointmentPDFProps {
  taskTitle: string;
  taskDetails: any;
}

export function AppointmentPDF({ taskTitle, taskDetails }: AppointmentPDFProps) {
  const { state } = useOnboarding();
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    setIsGenerating(true);

    const systemPrompt = `You are an expert UAE student advisor. Create a printable checklist for a student attending an appointment for: ${taskTitle}.
    
    Use the provided task details and student profile to generate a clean, professional HTML document.
    The HTML should be ready to print (A4 size, clean typography, checkboxes).
    Include:
    1. A clear header with the task name and student name.
    2. A "What to Bring" checklist (documents, IDs, fees).
    3. "Where to Go" details.
    4. "What to Expect" or "Pro Tips".
    
    Return ONLY the raw HTML string, no markdown formatting or extra text.`;

    const profileData = JSON.stringify({
      name: state.name,
      university: state.university,
      emirate: state.emirate,
    });

    const taskData = JSON.stringify(taskDetails);

    try {
      const htmlContent = await callAI(systemPrompt, `Profile: ${profileData}\nTask: ${taskData}`);
      
      // Clean up the response if it includes markdown blocks
      const cleanHtml = htmlContent.replace(/```html\n?/g, '').replace(/```\n?/g, '');

      // Open in a new window for printing
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>Appointment Checklist - ${taskTitle}</title>
              <style>
                body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.5; color: #1e293b; max-width: 800px; margin: 0 auto; padding: 40px; }
                h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
                h2 { color: #334155; margin-top: 30px; }
                ul { list-style-type: none; padding: 0; }
                li { margin-bottom: 10px; display: flex; align-items: flex-start; }
                li::before { content: "☐"; margin-right: 10px; font-size: 1.2em; color: #64748b; }
                .footer { margin-top: 50px; font-size: 0.8em; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 20px; }
                @media print {
                  body { padding: 0; }
                  button { display: none; }
                }
              </style>
            </head>
            <body>
              <div style="text-align: right; margin-bottom: 20px;">
                <button onclick="window.print()" style="padding: 10px 20px; background: #0f172a; color: white; border: none; border-radius: 6px; cursor: pointer;">Print Checklist</button>
              </div>
              ${cleanHtml}
              <div class="footer">Generated by LANDED AI Assistant</div>
            </body>
          </html>
        `);
        printWindow.document.close();
      }
    } catch (error) {
      console.error("Failed to generate PDF", error);
      alert("Failed to generate the checklist. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Button 
      onClick={handleGenerate} 
      disabled={isGenerating}
      variant="outline" 
      className="w-full sm:w-auto gap-2 border-slate-200 hover:bg-slate-50 text-slate-700"
    >
      {isGenerating ? (
        <Loader2 className="w-4 h-4 animate-spin" />
      ) : (
        <Printer className="w-4 h-4" />
      )}
      {isGenerating ? "Generating..." : "Print Checklist"}
    </Button>
  );
}
